package com.baxixiaomi.code.demo.webservice.client;

import javax.jws.WebMethod;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.4
 * 2019-12-17T23:22:15.226+08:00
 * Generated source version: 3.3.4
 *
 */
@WebService(targetNamespace = "http://server.webservice.baxixiaomi.com/", name = "SendMessage")
@XmlSeeAlso({ObjectFactory.class})
public interface SendMessage {

    @WebMethod
    @RequestWrapper(localName = "sendMessage", targetNamespace = "http://server.webservice.baxixiaomi.com/", className = "com.baxixiaomi.code.demo.webservice.server.SendMessage_Type")
    @ResponseWrapper(localName = "sendMessageResponse", targetNamespace = "http://server.webservice.baxixiaomi.com/", className = "com.baxixiaomi.code.demo.webservice.server.SendMessageResponse")
    public void sendMessage()
;
}
