
package com.baxixiaomi.code.demo.webservice.client;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;

import com.baxixiaomi.code.demo.webservice.server.SendMessage;
import com.baxixiaomi.code.demo.webservice.client.impl.SendMessageImplService;


/**
 * This class was generated by Apache CXF 3.3.4
 * 2019-12-17T23:22:15.184+08:00
 * Generated source version: 3.3.4
 * 通过apache-cxf自身生成客户端代码,通过本地cmd执行以下命令
 *
 * wsdl2java -d 指定生成的客户端代码路径 -client 发布服务的链接?wsdl
 *
 */
public final class SendMessageClient {

    private static final QName SERVICE_NAME = new QName("http://impl.server.webservice.baxixiaomi.com", "SendMessageImplService");

    private SendMessageClient() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = SendMessageImplService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        SendMessageImplService ss = new SendMessageImplService(wsdlURL, SERVICE_NAME);
        SendMessage port = ss.getSendMessageImplPort();

        {
        System.out.println("Invoking sendMessage...");
        port.sendMessage();


        }

        System.exit(0);
    }

}
