package com.baxixiaomi.code.demo.webservice.client.impl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import com.baxixiaomi.code.demo.webservice.server.SendMessage;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.3.4
 * 2019-12-17T23:22:15.235+08:00
 * Generated source version: 3.3.4
 *
 */
@WebServiceClient(name = "SendMessageImplService",
                  wsdlLocation = "http://localhost:12121?wsdl",
                  targetNamespace = "http://impl.server.webservice.baxixiaomi.com")
public class SendMessageImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://impl.server.webservice.baxixiaomi.com", "SendMessageImplService");
    public final static QName SendMessageImplPort = new QName("http://impl.server.webservice.baxixiaomi.com", "SendMessageImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:12121?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(SendMessageImplService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://localhost:12121?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public SendMessageImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SendMessageImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SendMessageImplService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public SendMessageImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public SendMessageImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public SendMessageImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns SendMessage
     */
    @WebEndpoint(name = "SendMessageImplPort")
    public SendMessage getSendMessageImplPort() {
        return super.getPort(SendMessageImplPort, SendMessage.class);
    }

    /**
     *
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SendMessage
     */
    @WebEndpoint(name = "SendMessageImplPort")
    public SendMessage getSendMessageImplPort(WebServiceFeature... features) {
        return super.getPort(SendMessageImplPort, SendMessage.class, features);
    }

}
